import { Transaction } from '@/lib/types';
import { format } from 'date-fns';

export function buildReportHtml(flagged: Transaction[]): string {
  const sorted = [...flagged].sort((a, b) => b.riskScore - a.riskScore);
  const confirmed = flagged.filter(t => t.status === 'confirmed_fraud');
  const confirmedAmt = confirmed.reduce((s, t) => s + t.amount, 0);
  const pending = flagged.filter(t => t.status === 'pending').length;
  const now = new Date();
  const top3 = sorted.slice(0, 3);

  return `
    <div style="font-family:monospace;max-width:700px;margin:0 auto;padding:24px;background:#0a0a0a;color:#e5e5e5;border-radius:8px;">
      <h1 style="color:#ef4444;font-size:20px;border-bottom:2px solid #333;padding-bottom:12px;">
        ⚠ AI SENTINEL — INCIDENT REPORT
      </h1>
      <p style="color:#888;font-size:12px;">Generated: ${format(now, 'PPpp')}</p>

      <h2 style="color:#f59e0b;font-size:14px;margin-top:20px;">EXECUTIVE SUMMARY</h2>
      <table style="width:100%;border-collapse:collapse;font-size:13px;">
        <tr><td style="padding:6px;border-bottom:1px solid #333;">Total Flagged</td><td style="padding:6px;border-bottom:1px solid #333;font-weight:bold;">${flagged.length}</td></tr>
        <tr><td style="padding:6px;border-bottom:1px solid #333;">Confirmed Fraud</td><td style="padding:6px;border-bottom:1px solid #333;font-weight:bold;color:#ef4444;">${confirmed.length}</td></tr>
        <tr><td style="padding:6px;border-bottom:1px solid #333;">Pending Review</td><td style="padding:6px;border-bottom:1px solid #333;font-weight:bold;color:#f59e0b;">${pending}</td></tr>
        <tr><td style="padding:6px;border-bottom:1px solid #333;">Fraud Amount</td><td style="padding:6px;border-bottom:1px solid #333;font-weight:bold;color:#ef4444;">$${confirmedAmt.toLocaleString()}</td></tr>
      </table>

      <h2 style="color:#f59e0b;font-size:14px;margin-top:20px;">FLAGGED TRANSACTIONS</h2>
      <table style="width:100%;border-collapse:collapse;font-size:11px;">
        <tr style="background:#1a1a1a;">
          <th style="padding:6px;text-align:left;border-bottom:2px solid #333;">ID</th>
          <th style="padding:6px;text-align:left;border-bottom:2px solid #333;">User</th>
          <th style="padding:6px;text-align:left;border-bottom:2px solid #333;">Amount</th>
          <th style="padding:6px;text-align:left;border-bottom:2px solid #333;">Location</th>
          <th style="padding:6px;text-align:left;border-bottom:2px solid #333;">Risk</th>
          <th style="padding:6px;text-align:left;border-bottom:2px solid #333;">Status</th>
        </tr>
        ${sorted.map(t => `
          <tr style="border-bottom:1px solid #222;">
            <td style="padding:4px;font-family:monospace;">${t.id}</td>
            <td style="padding:4px;">${t.userId}</td>
            <td style="padding:4px;">$${t.amount.toLocaleString()}</td>
            <td style="padding:4px;">${t.location.name}</td>
            <td style="padding:4px;color:${t.riskScore >= 70 ? '#ef4444' : '#f59e0b'};">${t.riskScore}</td>
            <td style="padding:4px;">${t.status.replace('_', ' ')}</td>
          </tr>
        `).join('')}
      </table>

      <h2 style="color:#f59e0b;font-size:14px;margin-top:20px;">RECOMMENDED ACTIONS</h2>
      ${top3.map((t, i) => `
        <div style="background:#1a1a1a;border-left:3px solid #ef4444;padding:10px;margin:8px 0;border-radius:4px;">
          <strong style="color:#ef4444;">#${i + 1} [IMMEDIATE]</strong> ${t.id} — $${t.amount.toLocaleString()} from ${t.location.name} (Score: ${t.riskScore})<br/>
          <span style="color:#888;font-size:11px;">User: ${t.userId} · Device: ${t.deviceType} · Status: ${t.status}</span>
        </div>
      `).join('')}

      <p style="color:#555;font-size:10px;margin-top:24px;border-top:1px solid #333;padding-top:12px;">
        This is an automated report generated by AI Sentinel Fraud Detection System.
      </p>
    </div>
  `;
}
